LIFE_QUOTES  = [
    # quotes from https://www.psicoactiva.com/blog/frases-de-la-vida-para-reflexionar/
    "No se puede hacer nada para cambiar lo que ya pasó, pero sí se puede hacer mucho para cambiar lo que viene.",
    "Si caminas solo, irás más rápido. Si caminas acompañado, llegarás más lejos.",
    "Una vida llena de errores no solo es más honorable, sino que es más sabia que una vida gastada sin hacer nada.",
    "Es sencillo hacer que las cosas sean complicadas, pero difícil hacer que sean sencillas. F. Nietzsche",
    "Si no quieres sentirte frustrado, no te pongas metas imposibles.",
    "No pierdas nunca el sentido del humor y aprende a reírte de tus propios defectos.",
    "La capacidad para soportar la ansiedad es importante para la autorrealización del individuo y para la conquista de su entorno.",
    "El pasado es para aprender, el presente para vivirlo y el futuro para soñarlo.",
    "La realización de uno mismo solo se alcanza avanzando pese a los choques emocionales.",
    "Muchos de nuestros sueños parecen al principio imposibles, luego pueden parecer improbables, y luego, cuando nos comprometemos firmemente, se vuelven inevitables.",
    "Quien no ha caído nunca, no tiene una idea justa del esfuerzo que hay que hacer para tenerse en pie. Multatuli",
    "La vida es una oportunidad, benefíciate de ella. La vida es belleza, admírala. La vida es un sueño, alcánzalo. La vida es un desafío, enfréntalo. La vida es un juego, juégalo. Madre Teresa",
    "La preocupación es como una mecedora, te mantiene ocupado pero no te lleva a ninguna parte.",
    "Cuando cambias el modo en que ves las cosas, las cosas que ves cambian también. Wayne Dyer",
    "Un día de preocupación es más agotador que un día de trabajo. John Lubbock",
    "No puedes retorcerte las manos y arremangarte al mismo tiempo. Pat Schroeder",
    'No digas “me rechazó”, di “perdió la oportunidad”. No digas “nunca le gusté”, di “no me valoró”.No digas “terminó”, di “algo nuevo comenzará”.',
    "Hay momentos en los que miras atrás y no sabes exactamente qué pasó. Sólo sabes que, desde que pasó, nada volvió a ser lo mismo.",
    "Tú eres más fuerte que tus miedos. Tus fuerzas son mayores que tus dudas.",
    "Aunque tu mente esté confundida, tu corazón siempre sabe la respuesta.",
    "Con el tiempo, lo que hoy es difícil mañana será una conquista. Esfuérzate por lo que realmente te llena el alma. Y ten la virtud de saber esperar. Porque… todo lo que tiene que ser, será.",
    "Evita a las personas negativas; siempre tienen un problema para cada solución.",
    "Si no cambiamos la dirección de nuestros pasos, es muy probable que acabemos llegando allí donde nos dirigimos.",
    "El que no sabe lo que busca, no entiende lo que encuentra.",
    "Vive como si fueras a morir mañana, aprende como si fueras a vivir para siempre. James Dean",
    "La vida es un eco, si no te gusta lo que estás recibiendo, fíjate en lo que estás emitiendo.",
    "No anticipes los problemas ni te preocupes por lo que pueda suceder: mantente bajo la luz del sol. Benjamin Franklin",
    "No puedes retorcerte las manos y arremangarte al mismo tiempo. Pat Schroeder",
    "Cuando algo malo te suceda, tienes tres opciones: Dejar que te marque. Dejar que te destruya. Dejar que te fortalezca.",
    "Uno es dueño de lo que calla y esclavo de lo que habla. Sigmund Freud",
    "Nadie se da cuenta de que hay alguna gente que gasta excesiva energía simplemente para parecer normal. Albert Camus",
    "Algunos buscan la felicidad, otros la crean…",
    "No existe mejor pregunta que una mirada, ni mejor respuesta que una sonrisa…",
    "Importa mucho más lo que tu pienses de ti mismo, que lo que los demás opinen de ti.",
    "Es una locura odiar a todas las rosas porque una de ellas te pinchó. Renunciar a todos tus sueños, porque uno de ellos no se realizó. El principito.",
    "La gente puede fingir durante unos días, pero no durante toda una vida.",
    "Muchas veces es mejor olvidar lo que uno siente, y recordar lo que uno vale.",
    "No tienes que controlar tus pensamientos; solo tienes que dejar de permitirles que te controlen a ti. Dan Millman",
    "Una mentira es como una bola de nieve; cuanto más rueda, más grande se vuelve.",
    "Cuando saco a una persona de mi vida, no significa que la odie, significa que me respeto.",
    "La primera vez que me engañes, será culpa tuya; la segunda vez, la culpa será mía.",
    "Solo hay dos errores que se comenten en el camino a la verdad: No empezar, y no llegar hasta el final.",
    "Si no cambiamos, no crecemos, si no crecemos no estamos vivos.",
    "La realidad no es lo que nos sucede, sino lo que hacemos con lo que nos sucede. Huxley, A",
    "Muchas veces en la vida las personas olvidan lo que deben recordar, y recuerdan lo que deben olvidar.",
    "Lo que tu tienes, muchos lo pueden tener, pero lo que tu eres, nadie lo puede ser…",
    "Acaba ya con los celos, la envidia, las obsesiones y trabaja tu autoestima porque es en tu propia valía en donde encontrarás tu equilibrio.",
    "Así como hay cosas que pasan por algo, hay otras cosas que por algo… no pasan.",
    "La desconfianza en los propios valores crea indefensión y dependencia en los otros.",
    "Las amenazas a nuestra autoestima o la idea que nos hacemos de nosotros mismos, causan con frecuencia mucha más ansiedad que las amenazas a nuestra integridad física.",
    "No te quedes sentado esperando que lleguen las cosas a ti. Lucha por lo que quieres, hazte responsable de ti mismo.",
    "Cada dolor te hace más fuerte, cada traición más inteligente, cada desilusión más hábil y cada experiencia más sabio…",
    "Conocer a otros es inteligencia, conocerse a sí mismo es sabiduría. Manejar a otros es fuerza, manejarse a sí mismo es verdadero poder. Tao Te Ching.",
    "De todos los animales de la creación el hombre es el único que bebe sin tener sed, come sin tener hambre y habla sin tener nada que decir. John Steinbeck",
    "Todavía me emocionan ciertas voces, todavía creo en mirar a los ojos, todavía tengo en menta cambiar algo…",
    "A lo mejor no lloro, pero duele. A lo mejor no lo digo, pero siento. A lo mejor no lo demuestro, pero sí que me importa.",
    "En cuanto el cerebro humano fue capaz de concebir el futuro, se volvió capaz de sentir aprensión sobre el mismo.",
    "La capacidad de hacer planes y de imaginar el futuro, va de la mano con la capacidad de preocuparse, de temer al porvenir.",
    "El rechazo es un maestro en el arte de dibujar fronteras. No en vano, es tan doloroso como un puñetazo en la cara y tan infranqueable como un muro de hormigón.",
    "Detrás de cada línea de llegada, hay una de partida. Detrás de cada logro, hay otro desafío. Madre Teresa de Calcuta",
    "La mayoría de gente escucha con la intención de responder, no con la intención de comprender. A. C. Doyle",
    "Me encanta la gente que no cambia para agradar a nadie",
    "Algunas personas frías que parecen no importarles nada, son las que guardan mundos de sentimiento dentro",
    "No podremos encontrar paz en el mundo hasta que no estemos en paz con nosotros mismos. Dalai Lama.",
    "Persigue a las mariposas y nunca las atraparás. Observa a las mariposas y vendrán hasta ti…",
    "La mejor forma de superar los complejos es: convivir plácidamente con ellos.",
    "No se puede desatar un nudo… sin saber cómo está hecho.",
    "Cuando la vida te presente razones para llorar, demuéstrale que tienes mil y una razones para reír.",
    "Muchas veces en la vida las personas olvidan lo que deben recordar, y recuerdan lo que deben olvidar.",
    "No permitas que el mal comportamiento de otros destruya tu paz interior…",
    "La rigidez y el autoritarismo son tan enemigos de la relación como el darse por entero.",
    "Quien limita tu forma de ser, no te quiere por lo que eres, sino por lo que espera que seas.",
    "La fuerza no viene de la capacidad corporal, sino de la voluntad del alma. Gandhi",
    "Cuando el objetivo te parezca difícil, no cambies el objetivo; busca un nuevo camino para llegar a él. Confucio",
    "Tu bienestar y tu felicidad es mental. Cuida tu mente y rodéate de personas, actitudes y sentimientos positivos",
    "Nunca vayas por el camino trazado pues conduce hacia donde otros han ido ya. Alexander Graham Bell",
    "No se puede atravesar el mar simplemente mirando el agua. Rabindranath Tagore",
    "Nadie nace guapo ni feo, sólo que como hay gente que se aburre, califica a las personas como les parece y las mira por fuera no por dentro, que es dónde está la persona.",
    "Cuando cambias el modo en que ves las cosas, las cosas que ves cambian también. Wayne Dyer",
    "Fórmula antiestrés: primero no preocuparse por las cosas pequeñas y segundo recordar que casi todas las cosas en esta vida son pequeñas. Adam J. Jackson",
    "Sé cuidadoso con tus palabras, una vez dichas sólo pueden ser perdonadas, no olvidadas.",
    "Muchas veces es mejor olvidar lo que uno siente, y recordar lo que uno vale.",
    "No dejes que los ruidos de las opiniones de los demás acallen tu propia voz interior. Steve Jobs",
    "Nunca dejes de soñar, de los sueños está hecha la vida.",
    "Hemos construido un sistema que nos persuade a gastar dinero que no tenemos, en cosas que no necesitamos, para crear impresiones que no durarán en personas que no nos importan. Emile Herari Gauvreay",
    "Los bonitos recuerdos son como las luciérnagas… sólo basta una para eliminar la oscuridad.",
    "El envoltorio puede ser importante, el contenido debe serlo.",
    "El orgullo te podrá hacer sentir fuerte, pero jamás te hará sentir feliz",
    "Dicen que hay que ver para creer, así que ponte frente al espejo y empieza a creer en ti.",
    "El destino se escribe a lápiz.",
    "La vida es un misterio que hay que desvelar, no un problema que hay que resolver.",
    "Lo blando vence a lo duro, lo débil vence a lo fuerte. Lo maleable siempre es superior a lo inamovible. Según este principio, el control de las cosas se obtiene colaborando con ellas, y la supremacía se logra mediante la adaptación. Lao Tse.",
    "El problema es que pensamos demasiado en lo que pasó y en lo que pasará, cuando lo importante es lo que está pasando.",
    "En el momento en que empezamos a tomarnos nuestros fracasos con poca seriedad, en ese momentos empezamos a dejar de tenerles miedo.",
    "Siempre habrá ángeles en tus infiernos y tentaciones en tus paraísos.",
    "Si permitimos que alguien nos obligue a hacer algo, siempre somos nosotros los responsables.",
    "¡Dale sentido a tu vida! No dejes que ligeros deslices afecten o influyan en tu felicidad! La vida no es perfecta! de los errores se aprende y se toman como ejemplo para alcanzar tu paz y serenidad.",
    "El miedo al rechazo aparece ante la posibilidad de perder la aprobación, la aceptación o el afecto de la otra persona, temiendo por el sentimiento de abandono.",
    "No dejes que se muera el Sol sin que hayan muerto tus rencores. M. Gandhi",
    "La falta de esperanza en la vida no es un hecho, sólo un punto de vista.",
    "Cierra los ojos y piensa en 3 cosas por las cuales debes estar agradecido, cuando las halles, sabrás lo afortunado que eres en realidad.",
    "Tu mente es la mayor guionista de culebrones de la historia: se inventa relatos increíbles, generalmente basados en dramas y situaciones que jamás han ocurrido y probablemente nunca ocurrirán.",
    "Tú eres la raíz, los resultados son tus frutos.",
    "Los obstáculos que he tenido en mi vida, me han hecho madurar, los éxitos me han hecho reflexionar, y los fracasos me han hecho crecer.",
]


HARRY_POTTER_QUOTES = [
    # quotes from https://www.fotogramas.es/noticias-cine/a25215046/mejores-frases-harry-potter/
    '"No son nuestras habilidades las que muestran cómo somos, sino nuestras elecciones” (Albus Dumbledore)',
    '"Eres un mago, Harry" (Hagrid)',
    '"Las palabras son, en mi no tan humilde opinión, nuestra más inagotable fuente de magia, capaces de infringir daño y de remediarlo" (Albus Dumbledore)',
    '“Si quieres saber en verdad como una persona es, échale una mirada a cómo trata a sus inferiores, no a sus iguales” (Sirius Black)',
    '“Juro solemnemente que mis intenciones no son buenas” (Mapa del Merodeador)',
    '"Me voy a la cama antes de que a alguno de los dos se os ocurra otra genial idea y acabemos muertos. O peor: expulsados" (Hermione Granger)',
    '"No todos los magos son buenos, algunos se malogran" (Hagrid)',
    '"Siempre" (Severus Snape)',
    '"Lo que perdemos al final siempre vuelve a nosotros... aunque a veces no del modo que esperamos" (Luna Lovegood)',
    '"La curiosidad no es un pecado, Harry, pero debemos ser cautos con ella" (Albus Dumbledore)',
    '"Todos tenemos luz y oscuridad en nuestro interior: lo que importa es qué parte decidimos potenciar" (Sirius Black)',
    '"Draco dormiens nunquam titillandus (Nunca le hagas cosquillas a un dragón dormido)" (Lema de Hogwarts)',
    '"Harry, lo que importa no son vuestras similitudes, sino vuestras diferencias" (Albus Dumbledore)',
    '"Nunca se irá del todo, no mientras haya quien le guarde lealtad" (Harry Potter)',
    '"Dobby no mata, sólo mutila o hiere de gravedad" (Dobby)',
    '"Es leviósa. No leviosá" (Hermione Granger)',
    '"No sirve de nada preocuparse. Lo que venga vendrá, y le plantaremos cara" (Hagrid)',
    '"La grandeza inspira envidia, la envidia engendra rencor y el rencor genera mentiras" (Voldemort)',
    '"La felicidad puede hallarse hasta en los más oscuros momentos, si somos capaces de usar bien la luz" (Albus Dumbledore)',
    '"No te estás volviendo loco. Yo también los veo. Estás tan cuerdo como yo" (Luna Lovegood)',
    '"Tú eres el débil, porque nunca conocerás el amor o la amistad" (Harry Potter)',
    '"El bien y el mal no existen. Sólo existe el poder y aquellos demasiado débiles para buscarlo" (Profesor Quirrell)',
    '"Seremos fuertes a medida que estemos unidos, débiles a medida que estemos divididos" (Albus Dumbledore)',
    '"¿Qué es la vida sin un poco de riesgo?” (Sirius Black)',
    '"No hay luz sin oscuridad. Y yo siempre procuro que entre la luz" (Slughorn)',
    '"Hay que tener mucho valor para oponernos a nuestros enemigos, pero mucho más para desafiar a nuestros amigos" (Albus Dumbledore)',
    '"No quiero que te sientas presionado, pero si no te ponen en Gryffindor, te desheredo" (Ron Weasley)',
    '"Oscuros y difíciles tiempos nos aguardan. Pronto todos tendremos que elegir entre lo que es correcto y lo que es fácil" (Albus Dumbledore)',
    '"No se deben decir mentiras" (Dolores Umbridge)',
    '"Mi filosofía es que el que teme sufre dos veces, por eso no hay nada que temer" (Newt Scamander)',
    '“Tienes la capacidad emocional de un ladrillo” (Hermione Granger)',
    '"Eres una buena persona a la que le han sucedido cosas malas" (Sirius Black)',
    '¡Qué techo más ridículo! (Alastor Moody)',
    '"No sientas pena de los muertos, sino de los vivos, y sobre todo de aquellos que viven sin amor" (Albus Dumbledore)',

    # quotes from https://genial.guru/creacion-arte/las-mejores-25-frases-de-harry-potter-145105/
    'La felicidad se puede hallar hasta en los más oscuros momentos, si somos capaces de usar bien la luz.',
    'Son nuestras elecciones las que muestran lo que somos, mucho más que nuestras habilidades.',
    'No es bueno dejarse arrastrar por los sueños y olvidarse de vivir.',
    'No sientas pena de los muertos, sino de los vivos, y sobre todo de aquellos que viven sin amor.',
    'Hay muchos tipos de valentía. Hay que tener un gran coraje para oponerse a nuestros enemigos, pero hace falta el mismo valor para hacerlo con los amigos.',
    'Para una mente bien preparada la muerte es solo la siguiente gran aventura.',
    'Es hora de elegir entre lo que es facil y lo que es correcto.',
    'Las palabras son, en mi no tan humilde opinión, nuestra más inagotable fuente de magia, capaces de infringir daño y de remediarlo...',
    'El amor es una fuerza que es más hermosa y más terrible que la muerte.',
    '¡No te das cuenta de que no importa lo que uno es por nacimiento, sino lo que uno es por sí mismo!',
    'Lo único que nos da miedo cuando nos asomamos a la muerte o a la oscuridad, es lo desconocido.',
    'Claro que esto sucede en tu cabeza Harry, pero ¿por qué eso tiene que significar que no es real?',
    'Llámalo Voldemort, Harry. Utiliza siempre el nombre correcto de las cosas. El miedo a un nombre aumenta el miedo a la cosa que se nombra.',
    'Los jóvenes no pueden saber cómo piensan ni cómo se sienten los ancianos, pero los ancianos somos culpables si olvidamos qué significa ser joven.',
    'Lema de Hogwarts: "Draco dormiens nunquam titillandus" Significa: "Nunca le hagas cosquillas a un dragón dormido".',
    'La verdad es una cosa terrible y hermosa, y por lo tanto debe ser tratada con gran cuidado.',
    'Tu incapacidad de comprender que hay cosas mucho peores que la muerte siempre ha sido tu mayor debilidad.',
    'La gente encuentra más fácil perdonar a los demás por equivocarse, que por acertar.',
    'La comprensión es el primer paso para la aceptación, y solo aceptando puede recuperarse.',
    '¿Piensas que los muertos a los que hemos querido nos abandonan del todo? ¿No crees que los recordamos especialmente en los mayores apuros? Tu padre vive en ti, Harry, y se manifiesta más claramente cuando lo necesitas.',
    'Ser el Maestro de la Muerte no es conseguir la inmortalidad. Es aceptar la muerte, esto es conquistarla.',
    '¡Todo el dinero y la vida que uno pueda desear! Las dos cosas que la mayor parte de los seres humanos elegirían… El problema es que los humanos tienen el don de elegir precisamente las cosas que son peores para ellos.',
    'Seremos fuertes a medida que estemos unidos, débiles a medida que estemos divididos… el don de esparcir discordia y enemistad es muy grande… podemos combatirlo demostrando un lazo de amistad y confianza igualmente fuertes.',
    'Las consecuencias de nuestras acciones son siempre tan complicadas, tan diversas, que predecir el futuro resulta ser un negocio muy difícil en sí.',
    'Y ahora, Harry, adentrémonos en la oscuridad y vayamos en busca de la aventura, aquella caprichosa seductora.',
]

LORD_OF_THE_RINGS_QUOTES = [
    # quotes from https://www.frasess.net/frases-de-el-senor-de-los-anillos-559.html
    'Y ciertas cosas que no deberían haber sido olvidadas se perdieron.',
    'El corazón de los hombres se corrompe con facilidad.',
    'No es algo malo celebrar una vida simple.',
    'Esa herida nunca sanará del todo. La llevará el resto de su vida.',
    'Un mago nunca llega tarde, Frodo Bolsón. Tampoco llega temprano. Llega precisamente a la hora que quiere.',
    'Se me ocurrió un final para mi libro: "Y vive feliz para siempre hasta el final de sus días".',
    'Hay una maldad ahí que nunca duerme. Y el Gran Ojo siempre está atento.',
    'Nueve compañeros. Que así sea. Serán la Comunidad del Anillo.',
    'Un anillo para gobernarlos a todos. Un anillo para encontrarlos. Un anillo para atraerlos a todos y en las tinieblas, atarlo.',
    'Si puedo atravesar el río, el poder de mi gente lo protegerá. No les temo.',
    'Extraño la Comarca. Pasé toda mi niñez fingiendo que estaba en otro lado. Que me había ido contigo, en una de tus aventuras. Pero mi propia aventura resultó muy distinta.',
    'Prefiero compartir una vida contigo que encarar todas las edades de este mundo yo sola. Yo escojo una vida mortal.',
    'Puedo dárselo a quien yo quiera. Igual que mi corazón.',
    'Si con mi vida o muerte te puedo proteger, lo haré. Tienes mi espada.',
    'Qué extraña suerte, tener que sufrir tanto miedo y tantas dudas por una cosa tan pequeña. Una cosa tan pequeñita.',
    'Perdóname por haberte acarreado esto. Perdóname por obligarte a llevar este peso. Perdóname por todo.',
    'Odia y ama el anillo tanto como se odia y se ama a sí mismo.',
    'Sólo podemos decidir qué hacer con el tiempo que se nos da.',
    'Muchos que viven merecen la muerte. Y algunos que mueren merecen la vida.',
    'Hasta la persona más pequeña puede cambiar el curso del futuro.',
    '¡Corred, insensatos!',
    'No temo ni al dolor ni a la muerte. (Temo) a una jaula, a empuñar sus barrotes hasta que la edad y la costumbre los acepten, toda opción al valor ceda al recuerdo y al deseo.',
    'Lleva mucho tiempo pronunciar algo en lengua Ent, y nunca decimos nada a menos que merezca la pena el tiempo que requiere decirlo.',
    'Tiempos aciagos me ha tocado vivir. Los jóvenes perecen, los ancianos se consumen.',
    'Trescientas vidas de hombre he transitado esta tierra y ahora me falta tiempo.',
    'Muchos de estos árboles eran amigos míos. Criaturas que conocía desde que eran semillas y bellotas.',
    'Soy Gandalf el blanco y en los albores de la tempestad, vuelvo a vosotros.',
    'Llegará el tiempo del honor sin reconocimiento.',
    'Espera mi llegada con la primera luz del 5º dia, al alba, mira al este.',
    '¿Qué asuntos traen a un elfo, un hombre y un enano a La Comarca?',
    'Los traicioneros son siempre desconfiados.',
    'No diré: "No lloréis", pues no todas las lágrimas son amargas.',
    'No vi mentira en los ojos de Pippin. Es un tonto, pero sigue siendo un tonto honesto.',
    'No dudo de su corazón, sólo del alcance de su brazo.',
    'Los Muertos no toleran que los vivos pasen.',
    'La muerte sólo es otro camino, uno que todos debemos tomar.',
    '¿Cómo retomas el hilo de una vida vieja?',
    'Hay ciertas cosas que el tiempo no puede curar.',
    '¿Cómo continúas cuando en tu corazón empiezas a entender que no hay manera de regresar?',
    'Sé aquello para lo que has nacido.',
    'No es más que la sombra de una ilusión lo que amas. No puedo darte lo que anhelas.',
    'Varias cosas sí son seguras. Si le abandono ahora, me arrepentire eternamente.',
    'Pero al final, todo es pasajero. Como esta sombra, incluso la oscuridad se acaba, para dar paso a un nuevo día. Y cuando el sol brilla, brilla más radiante aún.',
    'En este día lucharemos, por todo aquello que vuestro corazón ama de esta buena tierra, os llamo a luchar hombres del oeste.',
    'Caerán las lanzas, se quebrarán los escudos. Aún restará la espada. Rojo será el día hasta el nacer del sol.',
    '¡Águilas! ¡Las Águilas han venido!',
    '¿Se acuerda de La Comarca señor Frodo? Será pronto primavera. Los huertos estarán todos en flor y en la Avellaneda los pájaros tendrán listos sus nidos.',
    'Veo en vuestra mirada el miedo que encogería mi corazón.',
]

STAR_WARS_QUOTES = [
    # quotes from https://as.com/tikitakas/2021/05/04/portada/1620128389_104265.html
    '“Que la fuerza te acompañe”, Obi-Wan.',
    '“Su carencia de fe resulta molesta”, Darth Vader.',
    '“Tus ojos pueden engañarte, no confíes en ellos”, Obi-Wan a Luke.',
    '“¿Puede alguien quitarme de delante a este felpudo con patas?”, La Princesa Leia refiriéndose a Chewbacca.',
    '“No. No lo intentes. Hazlo, o no lo hagas, pero no lo intentes”, Maestro Yoda.',
    '“Yo soy tu padre”, Darth Vader.',
    '“Únete a mí y juntos dominaremos la Galaxia como padre e hijo”, Darth Vader.',
    '“Chewie ... estamos en casa”, Han, volviendo al Halcón Milenario.',
    '“Deja que el pasado muera. Mátalo, si es necesario”, Kylo Ren.',
    '«Así muere la libertad, con un estruendoso aplauso”, Padmé Amidala.',
    '“El miedo es el camino hacia el Lado Oscuro. El miedo lleva a la ira, la ira lleva al odio, el odio lleva al sufrimiento. Percibo mucho miedo en ti”, Maestro Yoda.',
    '“Soy prisionero del beso que nunca debiste haberme dado”, Anakin Skywalker.',
    '“La capacidad de hablar no te hace inteligente”, Qui-Gon Jinn a Jar Jar Binks.',
    '“No importa cuánto hayamos peleado. Siempre he odiado verte partir”, la Princesa Leia a Han Solo.',
    '“Actúa solo cuando puedas mantener el equilibrio”, Luc Skywalker.',
    '“Ningún campo de energía mística controla mi destino. Todo eso no son más que leyendas y tonterías”, Han Solo.',
    '“Así es cómo se gana una guerra. No luchando contra lo que odias, sino salvando lo que amas”, Roste Tico.',
    '“¿Quién es más loco: el loco o el loco que sigue al loco?”, Obi-Wan.',
    '“Concéntrate en el momento. Siente, no pienses, usa tu instinto”, Qui-Gon Jinn a Anakin Skywalker.',
    '“Sin duda, maravillosa la mente de un niño es”, Yoda refiriéndose a la respuesta de un pequeño padawan.',
    '“La guerra no lo hace a uno más grandioso”, Yoda a Luke Skywalker.',
]

ALL_QUOTES = LIFE_QUOTES.copy()

ALL_QUOTES.extend([quote + " [Harry Potter]" for quote in HARRY_POTTER_QUOTES])
ALL_QUOTES.extend([quote + " [El señor de los anillos]" for quote in LORD_OF_THE_RINGS_QUOTES])
ALL_QUOTES.extend([quote + " [Star Wars]" for quote in STAR_WARS_QUOTES])
