QUOTES  = [
    # quotes from https://www.psicoactiva.com/blog/frases-de-la-vida-para-reflexionar/
    "No se puede hacer nada para cambiar lo que ya pasó, pero sí se puede hacer mucho para cambiar lo que viene.",
    "Si caminas solo, irás más rápido. Si caminas acompañado, llegarás más lejos.",
    "Una vida llena de errores no solo es más honorable, sino que es más sabia que una vida gastada sin hacer nada.",
    "Es sencillo hacer que las cosas sean complicadas, pero difícil hacer que sean sencillas. F. Nietzsche",
    "Si no quieres sentirte frustrado, no te pongas metas imposibles.",
    "No pierdas nunca el sentido del humor y aprende a reírte de tus propios defectos.",
    "La capacidad para soportar la ansiedad es importante para la autorrealización del individuo y para la conquista de su entorno.",
    "El pasado es para aprender, el presente para vivirlo y el futuro para soñarlo.",
    "La realización de uno mismo solo se alcanza avanzando pese a los choques emocionales.",
    "Muchos de nuestros sueños parecen al principio imposibles, luego pueden parecer improbables, y luego, cuando nos comprometemos firmemente, se vuelven inevitables.",
    "Quien no ha caído nunca, no tiene una idea justa del esfuerzo que hay que hacer para tenerse en pie. Multatuli",
    "La vida es una oportunidad, benefíciate de ella. La vida es belleza, admírala. La vida es un sueño, alcánzalo. La vida es un desafío, enfréntalo. La vida es un juego, juégalo. Madre Teresa",
    "La preocupación es como una mecedora, te mantiene ocupado pero no te lleva a ninguna parte.",
    "Cuando cambias el modo en que ves las cosas, las cosas que ves cambian también. Wayne Dyer",
    "Un día de preocupación es más agotador que un día de trabajo. John Lubbock",
    "No puedes retorcerte las manos y arremangarte al mismo tiempo. Pat Schroeder",
    'No digas “me rechazó”, di “perdió la oportunidad”. No digas “nunca le gusté”, di “no me valoró”.No digas “terminó”, di “algo nuevo comenzará”.',
    "Hay momentos en los que miras atrás y no sabes exactamente qué pasó. Sólo sabes que, desde que pasó, nada volvió a ser lo mismo.",
    "Tú eres más fuerte que tus miedos. Tus fuerzas son mayores que tus dudas.",
    "Aunque tu mente esté confundida, tu corazón siempre sabe la respuesta.",
    "Con el tiempo, lo que hoy es difícil mañana será una conquista. Esfuérzate por lo que realmente te llena el alma. Y ten la virtud de saber esperar. Porque… todo lo que tiene que ser, será.",
    "Evita a las personas negativas; siempre tienen un problema para cada solución.",
    "Si no cambiamos la dirección de nuestros pasos, es muy probable que acabemos llegando allí donde nos dirigimos.",
    "El que no sabe lo que busca, no entiende lo que encuentra.",
    "Vive como si fueras a morir mañana, aprende como si fueras a vivir para siempre. James Dean",
    "La vida es un eco, si no te gusta lo que estás recibiendo, fíjate en lo que estás emitiendo.",
    "No anticipes los problemas ni te preocupes por lo que pueda suceder: mantente bajo la luz del sol. Benjamin Franklin",
    "No puedes retorcerte las manos y arremangarte al mismo tiempo. Pat Schroeder",
    "Cuando algo malo te suceda, tienes tres opciones: Dejar que te marque. Dejar que te destruya. Dejar que te fortalezca.",
    "Uno es dueño de lo que calla y esclavo de lo que habla. Sigmund Freud",
    "Nadie se da cuenta de que hay alguna gente que gasta excesiva energía simplemente para parecer normal. Albert Camus",
    "Algunos buscan la felicidad, otros la crean…",
    "No existe mejor pregunta que una mirada, ni mejor respuesta que una sonrisa…",
    "Importa mucho más lo que tu pienses de ti mismo, que lo que los demás opinen de ti.",
    "Es una locura odiar a todas las rosas porque una de ellas te pinchó. Renunciar a todos tus sueños, porque uno de ellos no se realizó. El principito.",
    "La gente puede fingir durante unos días, pero no durante toda una vida.",
    "Muchas veces es mejor olvidar lo que uno siente, y recordar lo que uno vale.",
    "No tienes que controlar tus pensamientos; solo tienes que dejar de permitirles que te controlen a ti. Dan Millman",
    "Una mentira es como una bola de nieve; cuanto más rueda, más grande se vuelve.",
    "Cuando saco a una persona de mi vida, no significa que la odie, significa que me respeto.",
    "La primera vez que me engañes, será culpa tuya; la segunda vez, la culpa será mía.",
    "Solo hay dos errores que se comenten en el camino a la verdad: No empezar, y no llegar hasta el final.",
    "Si no cambiamos, no crecemos, si no crecemos no estamos vivos.",
    "La realidad no es lo que nos sucede, sino lo que hacemos con lo que nos sucede. Huxley, A",
    "Muchas veces en la vida las personas olvidan lo que deben recordar, y recuerdan lo que deben olvidar.",
    "Lo que tu tienes, muchos lo pueden tener, pero lo que tu eres, nadie lo puede ser…",
    "Acaba ya con los celos, la envidia, las obsesiones y trabaja tu autoestima porque es en tu propia valía en donde encontrarás tu equilibrio.",
    "Así como hay cosas que pasan por algo, hay otras cosas que por algo… no pasan.",
    "La desconfianza en los propios valores crea indefensión y dependencia en los otros.",
    "Las amenazas a nuestra autoestima o la idea que nos hacemos de nosotros mismos, causan con frecuencia mucha más ansiedad que las amenazas a nuestra integridad física.",
    "No te quedes sentado esperando que lleguen las cosas a ti. Lucha por lo que quieres, hazte responsable de ti mismo.",
    "Cada dolor te hace más fuerte, cada traición más inteligente, cada desilusión más hábil y cada experiencia más sabio…",
    "Conocer a otros es inteligencia, conocerse a sí mismo es sabiduría. Manejar a otros es fuerza, manejarse a sí mismo es verdadero poder. Tao Te Ching.",
    "De todos los animales de la creación el hombre es el único que bebe sin tener sed, come sin tener hambre y habla sin tener nada que decir. John Steinbeck",
    "Todavía me emocionan ciertas voces, todavía creo en mirar a los ojos, todavía tengo en menta cambiar algo…",
    "A lo mejor no lloro, pero duele. A lo mejor no lo digo, pero siento. A lo mejor no lo demuestro, pero sí que me importa.",
    "En cuanto el cerebro humano fue capaz de concebir el futuro, se volvió capaz de sentir aprensión sobre el mismo.",
    "La capacidad de hacer planes y de imaginar el futuro, va de la mano con la capacidad de preocuparse, de temer al porvenir.",
    "El rechazo es un maestro en el arte de dibujar fronteras. No en vano, es tan doloroso como un puñetazo en la cara y tan infranqueable como un muro de hormigón.",
    "Detrás de cada línea de llegada, hay una de partida. Detrás de cada logro, hay otro desafío. Madre Teresa de Calcuta",
    "La mayoría de gente escucha con la intención de responder, no con la intención de comprender. A. C. Doyle",
    "Me encanta la gente que no cambia para agradar a nadie",
    "Algunas personas frías que parecen no importarles nada, son las que guardan mundos de sentimiento dentro",
    "No podremos encontrar paz en el mundo hasta que no estemos en paz con nosotros mismos. Dalai Lama.",
    "Persigue a las mariposas y nunca las atraparás. Observa a las mariposas y vendrán hasta ti…",
    "La mejor forma de superar los complejos es: convivir plácidamente con ellos.",
    "No se puede desatar un nudo… sin saber cómo está hecho.",
    "Cuando la vida te presente razones para llorar, demuéstrale que tienes mil y una razones para reír.",
    "Muchas veces en la vida las personas olvidan lo que deben recordar, y recuerdan lo que deben olvidar.",
    "No permitas que el mal comportamiento de otros destruya tu paz interior…",
    "La rigidez y el autoritarismo son tan enemigos de la relación como el darse por entero.",
    "Quien limita tu forma de ser, no te quiere por lo que eres, sino por lo que espera que seas.",
    "La fuerza no viene de la capacidad corporal, sino de la voluntad del alma. Gandhi",
    "Cuando el objetivo te parezca difícil, no cambies el objetivo; busca un nuevo camino para llegar a él. Confucio",
    "Tu bienestar y tu felicidad es mental. Cuida tu mente y rodéate de personas, actitudes y sentimientos positivos",
    "Nunca vayas por el camino trazado pues conduce hacia donde otros han ido ya. Alexander Graham Bell",
    "No se puede atravesar el mar simplemente mirando el agua. Rabindranath Tagore",
    "Nadie nace guapo ni feo, sólo que como hay gente que se aburre, califica a las personas como les parece y las mira por fuera no por dentro, que es dónde está la persona.",
    "Cuando cambias el modo en que ves las cosas, las cosas que ves cambian también. Wayne Dyer",
    "Fórmula antiestrés: primero no preocuparse por las cosas pequeñas y segundo recordar que casi todas las cosas en esta vida son pequeñas. Adam J. Jackson",
    "Sé cuidadoso con tus palabras, una vez dichas sólo pueden ser perdonadas, no olvidadas.",
    "Muchas veces es mejor olvidar lo que uno siente, y recordar lo que uno vale.",
    "No dejes que los ruidos de las opiniones de los demás acallen tu propia voz interior. Steve Jobs",
    "Nunca dejes de soñar, de los sueños está hecha la vida.",
    "Hemos construido un sistema que nos persuade a gastar dinero que no tenemos, en cosas que no necesitamos, para crear impresiones que no durarán en personas que no nos importan. Emile Herari Gauvreay",
    "Los bonitos recuerdos son como las luciérnagas… sólo basta una para eliminar la oscuridad.",
    "El envoltorio puede ser importante, el contenido debe serlo.",
    "El orgullo te podrá hacer sentir fuerte, pero jamás te hará sentir feliz",
    "Dicen que hay que ver para creer, así que ponte frente al espejo y empieza a creer en ti.",
    "El destino se escribe a lápiz.",
    "La vida es un misterio que hay que desvelar, no un problema que hay que resolver.",
    "Lo blando vence a lo duro, lo débil vence a lo fuerte. Lo maleable siempre es superior a lo inamovible. Según este principio, el control de las cosas se obtiene colaborando con ellas, y la supremacía se logra mediante la adaptación. Lao Tse.",
    "El problema es que pensamos demasiado en lo que pasó y en lo que pasará, cuando lo importante es lo que está pasando.",
    "En el momento en que empezamos a tomarnos nuestros fracasos con poca seriedad, en ese momentos empezamos a dejar de tenerles miedo.",
    "Siempre habrá ángeles en tus infiernos y tentaciones en tus paraísos.",
    "Si permitimos que alguien nos obligue a hacer algo, siempre somos nosotros los responsables.",
    "¡Dale sentido a tu vida! No dejes que ligeros deslices afecten o influyan en tu felicidad! La vida no es perfecta! de los errores se aprende y se toman como ejemplo para alcanzar tu paz y serenidad.",
    "El miedo al rechazo aparece ante la posibilidad de perder la aprobación, la aceptación o el afecto de la otra persona, temiendo por el sentimiento de abandono.",
    "No dejes que se muera el Sol sin que hayan muerto tus rencores. M. Gandhi",
    "La falta de esperanza en la vida no es un hecho, sólo un punto de vista.",
    "Cierra los ojos y piensa en 3 cosas por las cuales debes estar agradecido, cuando las halles, sabrás lo afortunado que eres en realidad.",
    "Tu mente es la mayor guionista de culebrones de la historia: se inventa relatos increíbles, generalmente basados en dramas y situaciones que jamás han ocurrido y probablemente nunca ocurrirán.",
    "Tú eres la raíz, los resultados son tus frutos.",
    "Los obstáculos que he tenido en mi vida, me han hecho madurar, los éxitos me han hecho reflexionar, y los fracasos me han hecho crecer.",
]
